---
- hosts: all
  become: true
  tags:
    - supervisor

  tasks:
    - name: Install Supervisor
      apt:
        name: supervisor
        update_cache: true

    - name: Create Supervisor Gunicorn programs
      template:
        src: "templates/supervisor/teameal_gunicorn.conf.j2"
        dest: "/etc/supervisor/conf.d/teameal_gunicorn.conf"

    - name: Ensure Supervisor programs are loaded
      supervisorctl:
        name: "teameal_gunicorn"
        state: present
